03_django/06_django_axios/accounts/urls.py
from django.urls import path
from . import views

app_name ='accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('<username>', views.profile, name='profile'), # 임의의 문자열을 읽어오는 주소이기 때문에 맨 아래에 있어야한다 위에 있으면 page not found 

]

03_django/06_django_axios/articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path('<int:article_pk>/comments/', views.comment_create, name='comment_create'), 
    path('<int:article_pk>/comments/<int:comment_pk>/comments_del/', views.comments_delete, name='comments_delete'),
    path('<int:article_pk>/like/', views.like, name='like'),
    path('<int:article_pk>/follow/<int:user_pk>/', views.follow, name='follow'),
    path('<int:hash_pk>/hashtag/', views.hashtag, name='hashtag'),

]

03_django/06_django_axios/myform/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
]

03_django/06_django_axios/articles/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

# Create your models here.
class Hashtag(models.Model):
    # 같은 해시태그가 작성되면 안됌(unique)
    # unique =True 인 경우 이 필드는 테이블 전체에서 고유한 값이어야 한다.
    # 유효성 검사 단계에서 실행되며 중복값이 있는 모델을 저장하려고 하면 .save()메서드로 인해 IntergrityError가 발생한다.
    # ManytoManyField 및 OneToOneField를 제외한 나머지에서 사용 가능 
    content = models.TextField(unique=True)

    def __str__(self):
        return self.content


class Article(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name= 'like_articles', blank=True)
    hashtags = models.ManyToManyField(Hashtag, blank=True)


    class Meta:
        ordering = ('-pk',)
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("articles:detail", kwargs={"article_pk": self.pk})

class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length= 140)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-pk']
    
    def __str__(self):
        return self.content
        # return f'<Article({self.article_id}): Comment({self.pk})-{self.content}'

03_django/06_django_axios/articles/forms.py
from django import forms
from .models import Article, Comment

# class ArticleForm(forms.Form):
#     title = forms.CharField(
#         max_length=10, 
#         label = '제목',
#         widget = forms.TextInput(attrs={
#             'class':'my-title',
#             'placeholder': 'Enter the Title'
#             }
#         )
#     )
#     content = forms.CharField(
#         label= '내용',
#         widget=forms.Textarea(
#             attrs={
#                 'class':'my-content',
#                 'placeholder': 'Enter the Content',
#                 'rows': 5,
#                 'cols': 50
#             }
#         )
#     )


class ArticleForm(forms.ModelForm):
    title= forms.CharField(
        label='제목',
        max_length=10,
        widget=forms.TextInput(
            attrs={
                'class':'my-title',
                'placeholder':'Enter the Title',
            }
        )
    )
    content = forms.CharField(
        label= '내용',
        widget=forms.Textarea(
            attrs={
                'class':'my-content',
                'placeholder': 'Enter the Content',
                'rows': 5,
                'cols': 50,
            }
        )
    )
    
    class Meta:
        model = Article
        fields = ('title','content',)
        # fields = '__all__'
        # exclude = ('title',)  제외해주기 
        # widgets ={
        #     'title' : forms.TextInput(attrs={}

        #     )
        # }

class CommentForm(forms.ModelForm):
        
    class Meta:
        model = Comment
        fields = ('content',)

03_django/06_django_axios/articles/views.py
import hashlib
from django.http import JsonResponse, HttpResponseBadRequest
from IPython import embed
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404, HttpResponse
from django.views.decorators.http import require_POST
from .models import Article, Comment, Hashtag
from .forms import ArticleForm, CommentForm
# Create your views here.
def index(request):
    # session 에 visits_num 키로 접근해 값을 가져온다.
    # 기본적으로 존재하지 않는 키이기 때문에 키가 없다면(방문한 적이 없다면) 0 값을 가져오도록 한다.
    visits_num = request.session.get('visits_num', 0)
    # 그리고 가져온 값을 session에  visits_num에 매번 1 씩 증가한 값으로 할당한다. (유저의 다음 방문을 위해)
    request.session['visits_num'] = visits_num + 1
    # session data 안에 있는 새로운 정보를 수정했다면 django는 수정한 사실을 알아채지 못하기 때문에 다은과 같이 설정
    request.session.modified = True
    articles = Article.objects.all()
    context = {'articles': articles, 'visits_num': visits_num,}
    return render(request, 'articles/index.html', context)


@login_required
def create(request):
    if request.method == 'POST':
        # form 인스턴트를 생성하고 요청에 의한 데이터를 인자로 받는다.(binding)
        # 이 처리 과정은 binding 이라고  불리며 유효성 체크를 할 수 있도록 해준다.
        form = ArticleForm(request.POST)
        # form이 유효한지 체크한다.
        if form.is_valid():
            # form.cleand_data 로 정제된 데이터를 받는다.
            article = form.save(commit=False)
            article.user_id = request.user.pk
            article.save()
            # hashtag 는 글이 저장된 이후에 작성해야한다. (써진 글을 보고 판단해야한다.)
            for word in article.content.split(): #content 를 공백 기준으로 리스트로 변경
                if word.startswith('#'): # '#'으로 시작하는 요소만 선택
                    hashtag, created = Hashtag.objects.get_or_create(content=word) # word랑 같은 해시태그를 찾는데 있으면 기존 객체(.get), 없으면 새로운 객체 생성(.create)
                    article.hashtags.add(hashtag) # create를 사용하지 않았다면, hashtag[0]으로 작성

            return redirect(article)
    else:
        form = ArticleForm()
    #  상황에 따라 context 에 넘어가는 2가지 form
    #  1. GET : 기본 form
    #  2. POST : 검증에 실패 후 의 form(is_vaild == False) 
    context = {'form':form,}
    return render(request, 'articles/form.html', context)

def detail(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    comments = article.comment_set.all() #article 의 모든 댓글
    person = get_object_or_404(get_user_model(), pk=article.user_id)
    comment_form = CommentForm() #댓글 폼
    context = {'article':article, 'comment_form':comment_form, 'comments':comments, 'person':person,}
    return render(request, 'articles/detail.html',context)

@require_POST
def delete(request, article_pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=article_pk)
        if request.user == article.user:
            article.delete()
        else:
            return redirect(article)
    return redirect('articles:index')
    
@login_required
def update(request, article_pk):
    article = get_object_or_404(Article, pk =article_pk)
    if request.user == article.user:
        if request.method == 'POST':
            form = ArticleForm(request.POST, instance=article)
            if form.is_valid():
                article = form.save()
                # hashtag 가 달린 글을 수정할 때는 모두 삭제한 후 다시 등록하는 방식으로
                article.hashtags.clear() # 해당 article의 hashtag 전체 삭제
                for word in article.content.split(): 
                    if word.startswith('#'): 
                        hashtag, created = Hashtag.objects.get_or_create(content=word)
                        article.hashtags.add(hashtag)
                return redirect(article)
        else:
            # ArticleForm 을 초기화 (이전에 DB에 저정된 데이터를 넣어준 상태)
            # form = ArticleForm(initial={'title':article.title, 'content':article.content})
            # __dict__ : article 객체 데이터를 딕셔너리 자료형으로 변환
            form = ArticleForm(instance=article)
        # 1. POST: 검증에 실패한 form(오류 메세지도 포함된 상태)
        # 2. GET: 초기화된 form
    else:
        return redirect('articles:index')
    context = {'form':form, 'article':article,}
    return render(request, 'articles/form.html', context)

@require_POST
def comment_create(request, article_pk):
    if request.user.is_authenticated:
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            # 객체를 create 하지만, db에 레코드는 작성하지 않는다.
            comment = comment_form.save(commit=False)
            comment.article_id = article_pk
            comment.user = request.user
            comment.save()
    return redirect('articles:detail', article_pk)
    

@require_POST
def comments_delete(request, article_pk, comment_pk):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, pk =comment_pk)
        if request.user == comment.user:
            comment.delete()
        return redirect('articles:detail', article_pk)
    return HttpResponse('You are Unauthorized', status=401)

@login_required
def like(request, article_pk):
    if request.is_ajax():
        article = get_object_or_404(Article, pk=article_pk)
        if article.like_users.filter(pk=request.user.pk).exists():
            article.like_users.remove(request.user)
            liked = False
        else:
            article.like_users.add(request.user)
            liked = True
        context = {'liked':liked, 'count':article.like_users.count(),}
        return JsonResponse(context)
    else:
        return HttpResponseBadRequest()


    # 해당 게시글에 좋아요를 누른 사람들 중에서 현재 접속유저가 있다면 좋아요를 취소
    # if request.user in article.like_users.all():
    #     article.like_users.remove(request.user) # 좋아요 취소
    # else:
    #     article.like_users.add(request.user) # 좋아요 
    

@login_required
def follow(request, article_pk, user_pk):
    person = get_object_or_404(get_user_model(), pk=user_pk)
    user = request.user
    if person != user:
    # 위 라잌이랑 똑같 , 내(request.user)가 게시글 유저 팔로워 목록에 이미 존재한다면, 
        if person.followers.filter(pk=user.pk).exists():
        #  if user in person.followers.all()
            person.followers.remove(user)
        else:
            person.followers.add(user)

    return redirect('articles:detail', article_pk)

def hashtag(request, hash_pk):
    hashtag = get_object_or_404(Hashtag, pk=hash_pk)
    articles = hashtag.article_set.order_by('-pk')
    context = {'hashtag':hashtag, 'articles':articles,}
    return render(request, 'articles/hashtag.html', context)

03_django/06_django_axios/articles/templates/articles/_article.html
<div class="card mb-3">
  <div class="card-header">
    작성자: <a class="card-link" href="{% url 'accounts:profile' article.user %}"> {{ article.user }} </a>
    <!--이게 실제로는 for문 안이라서 article사용 가능-->
  </div>
  <div class="card-body">
    <h5 class="card-title"><span style="font-size: 13px;">글 제목: </span>{{ article.title }}</h5>
    <p class="card-text">{{ article.pk }}</p>
    <hr>
    <p class="card-text">
      
        {% if user in article.like_users.all %}
        <i class="fab fa-gratipay fa-lg like-button" style="color: crimson;" data-id="{{ article.pk }}"></i>
        {% else %}
        <i class="fab fa-gratipay fa-lg like-button" style="color: black;" data-id="{{ article.pk }}"></i>
        {% endif %}
    
      <span id="like-count-{{ article.pk }}">{{ article.like_users.all|length }}</span>명이 이 글을 좋아합니다.
      <a href="{{ article.get_absolute_url }}" class="btn btn-outline-info float-right display-inline">DETAIL</a>
    <!--get_absolute_url의 reverse는 문자열로 리턴되는 것 그래서 {%가 아니라{{-->
    </p>
    
  </div>
</div>

03_django/06_django_axios/articles/templates/articles/_follow.html
<div class="jumbotron text-center">
  <h1 class="display-4">{{ person.username }}</h1>
  {% with  followings=person.followings.all followers=person.followers.all  %}
  <p class="lead">
    팔로잉 : {{ followings|length }} / 팔로워 : {{ followers|length }}
  </p>
  <hr class="my-4">
  {% if user != article.user %}
  {% if user in followers %}
  <a class="btn btn-primary btn-lg" href="{% url 'articles:follow' article.pk person.pk %}" role="button">Unfollow</a>
  {% else %}
  <a class="btn btn-primary btn-lg" href="{% url 'articles:follow' article.pk person.pk %}" role="button">Follow</a>
  {% endif %}
  {% endif %}
  {% endwith %}
</div>

03_django/06_django_axios/articles/templates/articles/_nav.html
{% load gravatar %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  {% if user.is_authenticated %}
    <a class="navbar-brand" href="{% url 'articles:index' %}">
    <img src="https://s.gravatar.com/avatar/{{ user.email|makemd5 }}?s=80" alt="프로필" width="30" height="30">
    Hello, {{ user.username }}
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link" href="{% url 'accounts:profile' user.username %}">
          프로필
        </a>
        <a class="nav-item nav-link" href="{% url 'accounts:update' %}">
          정보수정
        </a>
        <a class="nav-item nav-link" href="{% url 'accounts:change_password' %}">
          비밀번호 변경
        </a>
        <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">
          로그아웃
        </a>
        <form action="{% url 'accounts:delete' %}" method="POST" style="display: inline;">
          {% csrf_token %}
          <input type="submit" value="회원탈퇴" class="btn btn-danger">
        </form>
      </div>
    </div>
  
  {% else %}
    <a class="navbar-brand" href="{% url 'articles:index' %}">
    <img src="https://s.gravatar.com/avatar/{{ user.email|makemd5 }}?s=80" alt="프로필" width="30" height="30">
    Hello, STRANGER
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link" href="{% url 'accounts:login' %}">
          로그인
        </a>
        
        <a class="nav-item nav-link" href="{% url 'accounts:signup' %}">
          회원가입
        </a>
      </div>
    </div>
  {% endif %}
</nav>

03_django/06_django_axios/articles/templates/articles/base.html
{% load bootstrap4 %}
{% load gravatar %}


<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <script src="https://kit.fontawesome.com/8d76564a04.js" crossorigin="anonymous"></script>
  <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
  {% bootstrap_css %}
  <title>Document</title>
</head>

<body>
  <div class="container">
    {% include 'articles/_nav.html' %}
    {% block content %}
    {% endblock  %}
  </div>
  {% bootstrap_javascript jquery='full' %}
</body>

</html>

03_django/06_django_axios/articles/templates/articles/detail.html
{% extends 'articles/base.html' %}
{% load make_link %}
{% block content %}
<h1>DETAIL</h1>
<hr>
<p>{{ article.pk }}</p>
<p>{{ article.title }}</p>
<a>{{ article|hashtag_link|safe }}</p>
<p>{{ article.created_at|date:"SHORT_DATE_FORMAT" }}</p>
<p>{{ article.updated_at|date:"M, j, Y" }}</p>
{% if request.user == article.user %}
<a href="{% url 'articles:update' article.pk %}" method='POST'>[Update]</a>
<form action="{% url 'articles:delete' article.pk %}" method='POST' >
{% csrf_token %}
<input type="submit" value="DELETE">
</form>
{% endif %}
<hr>
<!--댓글 출력-->
{% for comment in comments %}
<div>댓글 {{ forloop.revcounter }} : {{ comment.content }}
{% if request.user == comment.user %}
<form action="{% url 'articles:comments_delete' article.pk comment.pk %}" method="POST" style="display: inline;">
{% csrf_token %}
<input type="submit" value="DELETE">
</form>
{% endif %}
</div>
{% empty %}
<p><b>댓글이 없습니다.</b></p>
{% endfor %}
<hr>
<!-- 댓글 작성 form-->
{% if request.user.is_authenticated %}
<form action="{% url 'articles:comment_create' article.pk %}" method="POST">
  {% csrf_token %}
  {{ comment_form }}
  <input type="submit" value="submit">
</form>
{% else %}
<a href="{% url 'accounts:login' %}">로그인 후 댓글을 작성해주세요.</a>
{% endif %}
<hr>
{% include 'articles/_follow.html' %}
<hr>

<a href="{% url 'articles:index' %}">[Back]</a>
{% endblock  %}

03_django/06_django_axios/articles/templates/articles/form.html
{% extends 'articles/base.html' %}
{% load bootstrap4 %}
{% block content %}

{% if request.resolver_match.url_name == 'create' %}
<h1>Create</h1>
{% else %}
<h1>Update</h1>
{% endif %}



<form action="" method="POST">
  {% csrf_token %}
  {% bootstrap_form form layout="horizontal"%}
  {% buttons %}
  {% buttons submit="OK" reset="Cancel" %}{% endbuttons %}
  {% endbuttons %}
</form>


{% if request.resolver_match.url_name == 'create' %}
<a href="{% url 'articles:index' %}">[Back]</a>
{% else %}
<a href="{{ article.get_absolute_url }}">[Back]</a>
{% endif %}
{% endblock  %}

03_django/06_django_axios/articles/templates/articles/hashtag.html
{% extends 'articles/base.html' %}
{% block content  %}

<div class="jumbotron jumbotron-fluid text-center my-2 text-white bg-dark">
  <div class="container">
    <h1 class="display-4">{{hashtag.content }}</h1>

    <p class="lead">{{ articles|length }} 개의 게시글</p>
  </div>
</div>
<hr>
<h3 class="text-center">{{hashtag.content }} 를 태그한 글</h3>
<div class="row">
{% for article in articles %}
{% with likes=article.like_users.all comments=article.comment_set.all %}
  <div class="col-4 my-2">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">{{ article.title }}</h5>
        <p class="card-text">{{ likes|length }} 명이 좋아요</p>
        <p class="card-text">{{ comments|length }} 개의 댓글</p>
        <a href="{% url 'articles:detail' article.pk %}" class="btn btn-success">해당 게시글로 이동</a>
      </div>
    </div>
  </div>
  {% endwith %}
  {% endfor %}
</div>








{% endblock  %}

03_django/06_django_axios/articles/templates/articles/index.html
{% extends 'articles/base.html' %}
{% block content %}
<h1>Articles</h1>
<p><b>당신의 방문 횟수 : {{ visits_num }} {% if visits_num == 1 %} time {% else %} times {% endif %} </b></p>
{% if user.is_authenticated %}
<a href="{% url 'articles:create' %}">[New!]</a>
{% else %}
<a href="{% url 'accounts:login' %}">[새 글을 작성하려면 로그인하세요.]</a>
{% endif %}

{% for article in articles %}
{% include 'articles/_article.html' %}
{% endfor %}
<script>
// 1. 각 게시글 별로 좋아요 버튼이 있으니 모두 선택해야한다.
const likebuttons = document.querySelectorAll('.like-button')
// 2. forEach를 사용해서 각각의 좋아요 버튼을 클릭
likebuttons.forEach(button => {
  button.addEventListener('click', function(event){
    //console.log(event)
    //event.target.dataset.id의 value 는 data-id 값이 들어있다
    const articleId = event.target.dataset.id
    // 해당 상세 게시글의 좋아요 요청을 보낸다.
    axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest'
    axios.defaults.xsrfCookieName = 'csrftoken'
    axios.defaults.xsrfHeaderName = 'X-CSRFToken'
    axios.post(`/articles/${articleId}/like/`)
      .then(response =>{
        document.querySelector(`#like-count-${articleId}`).innerText = response.data.count
        if (response.data.liked) {
          // 좋아요 색을 빨갛게
          event.target.style.color = 'crimson'
        } else {
          // 좋아요 색을 까맣게
          event.target.style.color = 'black'
        }
      }) 
      .catch(error => console.log(error))
  })
})

</script>

{% endblock  %}