PJT/PJT06/finder/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('movies/', include('movies.urls')),
    path('admin/', admin.site.urls),
]

PJT/PJT06/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/update/', views.update, name='update'),
    path('<int:movie_pk>/delete/', views.delete, name='delete'),
    path('<int:movie_pk>/reviews/', views.reviews_create, name='reviews_create'),
]

PJT/PJT06/movies/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=50)
    title_en = models.CharField(max_length=50)
    audience = models.IntegerField()
    open_date = models.DateField()
    genre = models.CharField(max_length=20)
    watch_grade = models.CharField(max_length=10)
    score = models.FloatField()
    poster_url = models.TextField()
    description = models.TextField()


    class Meta:
        ordering = ('-pk',)

    def __str__(self):
        return self.title


class Review(models.Model):
    movie = models.ForeignKey(Movie,on_delete=models.CASCADE)
    content = models.CharField(max_length= 140)
    score = models.IntegerField()

    class Meta:
        ordering = ['-pk']
        

    def __str__(self):
        return self.content

PJT/PJT06/movies/forms.py
from django import forms
from .models import Movie, Review
class MovieForm(forms.ModelForm):
    
    class Meta:
        model = Movie
        fields = '__all__'

class ReviewForm(forms.ModelForm):
    
    class Meta:
        model = Review
        fields = ("content","score",)

PJT/PJT06/movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from .models import Movie, Review
from .forms import MovieForm, ReviewForm
# Create your views here.


def index(request):
    movies = Movie.objects.all()
    context = {
        'movies': movies,
    }
    return render(request, 'movies/index.html', context)


def create(request):
    if request.method == 'POST':
        movie_form = MovieForm(request.POST)
        if movie_form.is_valid():
            movie = movie_form.save()
            return redirect('movies:detail', movie.pk)
    else:
        movie_form = MovieForm()
    context = {'movie_form': movie_form}
    return render(request, 'movies/form.html', context)


def detail(request, movie_pk):
    movie = get_object_or_404(Movie, pk = movie_pk)
    reviews = movie.review_set.all()
    review_form = ReviewForm()
    context = {
        'movie': movie,
        'reviews': reviews,
        'review_form': review_form,
    }
    return render(request, 'movies/detail.html', context)


def update(request, movie_pk):
    movie = get_object_or_404(Movie, pk = movie_pk)
    if request.method == 'POST':
        movie_form = MovieForm(request.POST, instance = movie)
        if movie_form.is_valid():
            movie = movie_form.save()
            return redirect('movies:detail', movie.pk)
    else:
        movie_form = MovieForm(instance = movie)
    context = {'movie_form': movie_form, 'movie': movie,}
    return render(request, 'movies/form.html', context)

@require_POST
def delete(request, movie_pk):
    movie = get_object_or_404(Movie, pk = movie_pk)
    movie.delete()
    return redirect('movies:index')

@require_POST
def reviews_create(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    if request.method =='POST':
        review_form = ReviewForm(request.POST)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.movie_id = movie_pk
            review.save()
    return redirect('movies:detail', movie.pk)

PJT/PJT06/movies/templates/movies/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
  <h1 class="text-center"> {{ movie.title }} </h1>
  <h3 class="text-center">{{ movie.title_en }} </h3>


<div class="card mx-auto" style="width: 30rem;">
  <img src="{{ movie.poster_url }}" class="card-img-top" alt="#">
  <hr>
  <div>
  <p>관람객 수 : {{ movie.audience }} </p>
  <p>개봉일 : {{ movie.open_date|date:"M, j, Y" }}</p>
  <p>장르 : {{ movie.genre }}</p>
  <p>관람 등급 : {{ movie.watch_grade }}</p> 
  <p>영화 평점 : {{ movie.score }}</p>
  <p>줄거리 :{{ movie.description }}</p>
  </div>
  <hr>


  <form action="{% url 'movies:reviews_create' movie.pk %}" method="POST">
    {% csrf_token %}
    {{ review_form }}
    {% buttons submit='OK' reset="Cancel" %}{% endbuttons %}
  </form>


  {% for review in reviews %}
    <li>
      리뷰 : {{ review.content }} 
      평점 : {{ review.score }}
  
  {% endfor %}
<hr>

  <a href="{% url 'movies:index' %}" class="btn btn-success"> 목록 </a>
  <a href="{% url 'movies:update' movie.pk %}" class="btn btn-success ">수정</a>
  <form action="{% url 'movies:delete' movie.pk %}" method="POST" >
  {% csrf_token %}
  {% buttons submit='삭제'%}{% endbuttons %}

  </form>
{% endblock content %}

PJT/PJT06/movies/templates/movies/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

{% if request.resolver_match.url_name == 'create' %}
<h1 class="m-3">새 영화 등록하기</h1>
{% else %}
<h1 class="m-3">영화 정보 수정하기</h1>
{% endif %}

<form action="" method="POST">
{% csrf_token %}
{% bootstrap_form movie_form layout="horizontal" %}
{% buttons submit='OK' reset="Cancel" %}
{% endbuttons %}
</form>

{% if request.resolver_match.url_name == 'create' %}
<a href="{% url 'movies:index' %}">뒤로 가기</a>
{% else %}
<a href="{% url 'movies:index' %}">뒤로 가기</a>
{% endif %}

{% endblock content %}

PJT/PJT06/movies/templates/movies/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1 class="text-center" style="margin-top:40px;">Movie recommendation</h1>
<div class="card bg-dark text-white">

  <img
    src="{% static 'movies/images/1.jpg' %}"
    class="card-img" alt="#" style="height:350px; width:100%;">
  <div class="card-img-overlay">
    <a href="{% url 'movies:create' %}" class="btn btn-success float-right" style="font-family: 'Jua', sans-serif;" >새 영화 등록</a><br>
  </div>
</div>
<br>
<hr>

<div class="row">
{% for  movie in movies  %}
  <div class="col-4">
  
  <div class="card bg-light m-1">
    <img src="{{ movie.poster_url }}" class="card-img-top"  alt="포스터이미지" width="100px">
    <a href="{% url 'movies:detail' movie.pk %}" class="card-header" style="font-family: 'Jua', sans-serif;">{{ movie.title }}</a>
   
      <h5 class="card-body">{{ movie.score }}</h5>

  </div>

  </div>
{% endfor %}
</div>
 
{% endblock content %}