03_django/06_django_axios/accounts/urls.py
from django.urls import path
from . import views

app_name ='accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('<username>', views.profile, name='profile'), # 임의의 문자열을 읽어오는 주소이기 때문에 맨 아래에 있어야한다 위에 있으면 page not found 

]

03_django/06_django_axios/articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path('<int:article_pk>/comments/', views.comment_create, name='comment_create'), 
    path('<int:article_pk>/comments/<int:comment_pk>/comments_del/', views.comments_delete, name='comments_delete'),
    path('<int:article_pk>/like/', views.like, name='like'),
    path('<int:article_pk>/follow/<int:user_pk>/', views.follow, name='follow'),
    path('<int:hash_pk>/hashtag/', views.hashtag, name='hashtag'),

]

03_django/06_django_axios/myform/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
]

03_django/06_django_axios/accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    # django 는 맞춤 모델을 참조하는 AUTH_USER_MODEL 설정 값을 제공함으로써
    # 기본 User 모델을 오버라이드 하도록 할 수 있다.
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='followings')

03_django/06_django_axios/articles/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

# Create your models here.
class Hashtag(models.Model):
    # 같은 해시태그가 작성되면 안됌(unique)
    # unique =True 인 경우 이 필드는 테이블 전체에서 고유한 값이어야 한다.
    # 유효성 검사 단계에서 실행되며 중복값이 있는 모델을 저장하려고 하면 .save()메서드로 인해 IntergrityError가 발생한다.
    # ManytoManyField 및 OneToOneField를 제외한 나머지에서 사용 가능 
    content = models.TextField(unique=True)

    def __str__(self):
        return self.content


class Article(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name= 'like_articles', blank=True)
    hashtags = models.ManyToManyField(Hashtag, blank=True)


    class Meta:
        ordering = ('-pk',)
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("articles:detail", kwargs={"article_pk": self.pk})

class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length= 140)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-pk']
    
    def __str__(self):
        return self.content
        # return f'<Article({self.article_id}): Comment({self.pk})-{self.content}'

03_django/06_django_axios/accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model() # return User
        fields = ('email','first_name','last_name',)

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model() # accounts.User
        fields = UserCreationForm.Meta.fields + ('email',)

03_django/06_django_axios/accounts/views.py
from IPython import embed
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.contrib.auth import login as auth_login, logout as auth_logout, update_session_auth_hash
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from .forms import CustomUserChangeForm, CustomUserCreationForm
# Create your views here.

def signup(request):
    if request.user.is_authenticated:
        return redirect('articles:index')
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            # form.save()를 통해 반환된 user 클래스의 인스턴스를 auth_login의 인자로 전달
            user = form.save()
            auth_login(request, user)
            return redirect('articles:index')

    else:
        form = CustomUserCreationForm()
    context = {'form':form,}
    return render(request, 'accounts/auth_form.html', context)

def login(request):
    if request.user.is_authenticated:
        return redirect('articles:index')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'articles:index')

    else:
        form = AuthenticationForm()
    context = {'form':form,}
    return render(request, 'accounts/login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('articles:index')

def delete(request):
    request.user.delete()
    return redirect('articles:index')

@login_required
def update(request):
    if request.method =='POST':
        form = CustomUserChangeForm(request.POST, instance = request.user)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {'form':form,}
    return render(request, 'accounts/auth_form.html', context)

@login_required
def change_password(request):
    if request.method =='POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('articles:index')
    else: 
        form = PasswordChangeForm(request.user)
    context = {'form':form,}
    return render(request, 'accounts/auth_form.html', context)


def profile(request, username):
    person = get_object_or_404(get_user_model(), username=username)
    context = {'person':person,}
    return render(request, 'accounts/profile.html', context)

03_django/06_django_axios/accounts/templates/accounts/auth_form.html
{% extends 'articles/base.html' %}
{% load bootstrap4 %}

{% block content %}
{% if request.resolver_match.url_name == 'signup' %}
<h1>회원가입</h1>
{% elif request.resolver_match.url_name == 'login' %}
<h1>로그인</h1>
{% elif request.resolver_match.url_name == 'update' %}
<h1>회원정보 수정</h1>
{% else %}
<h1>비밀번호 변경</h1>
{% endif %}

<form action="" method="POST">
{% csrf_token %}
{% bootstrap_form form layout="horizontal"%}
  {% buttons submit="회원가입" reset="Cancel" %}{% endbuttons %}
</form>
{% endblock  %}

03_django/06_django_axios/accounts/templates/accounts/change_password.html
{% extends 'articles/base.html' %}
{% load bootstrap4 %}

{% block content %}
<h1>비밀번호 변경 </h1>
<form action="" method="POST">
{% csrf_token %}
{% bootstrap_form form layout="horizontal"%}
  {% buttons submit="변경" reset="Cancel" %}{% endbuttons %}
</form>
{% endblock  %}

03_django/06_django_axios/accounts/templates/accounts/login.html
{% extends 'articles/base.html' %}
{% load bootstrap4 %}
{% load socialaccount %}

{% block content %}
<h1>Log in </h1>
<form action="" method="POST">
{% csrf_token %}
{% bootstrap_form form layout="horizontal"%}
  {% buttons submit="로그인" reset="Cancel" %}{% endbuttons %}
</form>
<a class="btn btn-warning" href="{% provider_login_url "kakao" %}">KakaoTalk</a>
{% endblock  %}

03_django/06_django_axios/accounts/templates/accounts/profile.html
{% extends 'articles/base.html' %}
{% block content %}
<h1 class="text-center">{{ person.username }}'s Profile</h1>
<hr>
<h3 class="text-center">{{ person.username }}이 작성한 글</h3>
<div class="row">
{% with articles=person.article_set.all %}
  {% for article in articles %}
  <div class="col-4 my-2">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"> {{ article.content }} </h5>
        <p class="card-text">{{ article.like_user.count }}명이 좋아하는 글 </p>
        <p class="card-text">{{ article.comment_set.all|length }}개의 댓글</p>
        <a href="{% url 'articles:detail' article.pk %}" class="btn btn-primary">게시글 보기</a>
      </div>
    </div>
  </div>
  {% endfor %}
  {% endwith %}
</div>
<hr>
<h3 class="text-center">{{ person.username }}이 작성한 댓글</h3>
<div class="row">
{% with person.comment_set.all as comments  %}
{% for comment in comments %}
  <div class="card">
    <div class="card-body">
      <div class="col-12 my-2">
        <blockquote class="blockquote mb-0">
          <p>{{ comment.content  }}</p>
          <footer class="blockquote-footer">{{ comment.created_at|date:"SHORT_DATE_FORMAT" }} </footer>
        </blockquote>
      </div>
    </div>
  </div>
  {% endfor %}
  {% endwith %}
</div>
{% endblock  %}

03_django/06_django_axios/accounts/templates/accounts/signup.html
{% extends 'articles/base.html' %}
{% load bootstrap4 %}

{% block content %}
<h1>Sign up</h1>
<form action="" method="POST">
{% csrf_token %}
{% bootstrap_form form layout="horizontal"%}
  {% buttons submit="회원가입" reset="Cancel" %}{% endbuttons %}
</form>
{% endblock  %}

03_django/06_django_axios/accounts/templates/accounts/update.html
{% extends 'articles/base.html' %}
{% load bootstrap4 %}

{% block content %}
<h1>회원정보수정</h1>
<form action="" method="POST">
{% csrf_token %}
{% bootstrap_form form layout="horizontal"%}
  {% buttons submit="정보수정" reset="Cancel" %}{% endbuttons %}
</form>
{% endblock  %}